### ISSUE TITLE
Pawprints returns a 500 error after signing in with RIT credentials

### ISSUE THREAD

**Issue by nerdy69420** [ritstudentgovernment/PawPrints-Archive#131]
I cannot view, sign, or create petitions using Pawprints. After signing in, I'm brought to a page with a 500 error. Clicking the 'report a problem' button does nothing. Especially as we rapidly approach the beginning of the Fall 2021 semester, Pawprints should be accessible for all students to propose ideas and voice their concerns.

My roommate also tried signing in to no avail.

**Comment by sgsvcs** [comment]
Pawprints is accessible as of early September 2021. Thanks for reporting the issue!
