### ISSUE TITLE
"Copy link" button is non-functional

### ISSUE THREAD

**Issue by Jack-Papel-RIT** [ritstudentgovernment/PawPrints-Archive#146]
On every petition, there is a "Share" section with four buttons: Facebook, Twitter, Reddit, and copy link.

However, it appears that the copy link button was never implemented. Clicking on it produces no effect, and hovering over it doesn't change the cursor. This always throws me for a loop, since the main way I share petitions with people is via the link.

Looking in the code for the page, it appears that while the other three buttons are `<a>` tags, the copy link button is just an `<img>`.

**Comment by MoralCode** [comment]
i investigated a little further. Looks like the button does work via javascript but it provides no indication that it does (via hover cursor change or any kind of animation).

see petitions/static/index.js:944
