### ISSUE TITLE
Petition delete button does nothing

### ISSUE THREAD

**Issue by Jack-Papel-RIT** [ritstudentgovernment/PawPrints-Archive#147]
On the profile page, in the petition section is a list of petitions created.

For each petition, there is a Delete button in the bottom right corner. However, clicking it only refreshes the page, and the petition is still there.

Using Chrome

**Comment by Sma-Das** [comment]
I've tested this myself on Chrome and I have not managed to replicate the behavior you've described.

Closing for now - if you have a video/gif demo showing the behavior, that would be great!
