### ISSUE TITLE
"Trending" sort doesn't sort by trending

### ISSUE THREAD

**Issue by Jack-Papel-RIT** [ritstudentgovernment/PawPrints-Archive#148]
If you sort by trending, the 1st place trending petition that pops up is "Close University On Wednesday And Thursday Due To Polar Vortex". This petition is from 2019. 

Since signing a petition is impossible after a petition has received a response, there is no possibility that this petition is "currently popular or widely discussed", as per the definition of trending. 

I think either the trending results should be changed to things that are actually trending, or the trending button should be changed to a "top" or "best" or "hot" button, as that more accurately describes the results.

**Comment by Sma-Das** [comment]
The button was intended to be used as a "most upvoted." I'm not sure where the choice came to have it represented by that icon but it's something that we can look into.
