### ISSUE TITLE
The link to request features for Pawprints is dead

### ISSUE THREAD

**Issue by H-Tevin** [ritstudentgovernment/PawPrints-Archive#167]
When creating a petition, there is a link to request a feature for Pawprints. This link leads nowhere and needs to be fixed so that suggestions can be submitted.
![image](https://user-images.githubusercontent.com/88856349/231006952-965cff37-f98a-450a-9d1c-088699290b00.png)
![image](https://user-images.githubusercontent.com/88856349/231006978-67bb3bf9-c037-4d8b-b788-33e5efcf2afa.png)
https://docs.google.com/forms/d/e/1FAIpQLScG4GbqWjHLs_PyzHtIqia0MCVsszTjbVOh3QHrmzhhWISgZQ/viewform?usp=send_form

**Comment by MoralCode** [comment]
this appears to be the same issue as #150

**Comment by Sma-Das** [comment]
We're currently debating the method by which that feedback can be communicated. 

We are open to suggestions too :)

**Comment by MoralCode** [comment]
> We're currently debating the method by which that feedback can be communicated.

Can you clarify what this means? Are you seeking feedback on what mechanism would be best to connect user feedback from this link to SG?

I'd love to encourage a process that also includes open source contributors like myself - i get that just publishing the form results may not be great, but i'd like to see them get converted into GitHub issues relatively quickly and have seen an automated solution before that could automatically create GitHub issues from an AirTable spreadsheet once a task was approved in case that is a solution that helps

**Comment by MoralCode** [comment]
@Sma-Das any updates on this?

**Comment by MoralCode** [comment]
this has been removed in https://github.com/ritstudentgovernment/PawPrints/commit/001822247c7ab947ff1b11bc02d0619bdbbd1df7

**Comment by H-Tevin** [comment]
Seems like the link was just deleted instead of making a new Google Form.
I don't support it, but I guess it did solve the issue.

**Comment by MoralCode** [comment]
At this point I would consider the feature request form to be this Github issue tracker. Google form is nice to enable people to make suggestions that arent on GitHub, so its a bit of a shame to lose that.
