### ISSUE TITLE
cannot log in

### ISSUE THREAD

**Issue by khipkin** [ritstudentgovernment/PawPrints-Archive#2]
I haven't been able to log into the pawprints site for months, but I just remembered that the site is actually open-source.

I try to log in using the button on the top of the page, then the little pop-up login box.
I enter my credentials, submit, and nothing happens.

However, there are tons of errors in the console:
![image](https://cloud.githubusercontent.com/assets/5641207/19333843/e698031c-90c5-11e6-89f0-5369071f2881.png)

More and more of the second type of errors generate as I wait... seems like there is a retry loop somewhere that just fails over and over again.

I'm running Chrome (![image](https://cloud.githubusercontent.com/assets/5641207/19333875/2e9d591e-90c6-11e6-9f3b-8156a112dc2f.png)) on Windows 10.

**Comment by khipkin** [comment]
Also, I do use AdBlock, but I turned it off for the entire pawprints.rit.edu/\* domain and was still unable to log in.

**Comment by zujko** [comment]
Thanks for taking the time to submit an issue! 
Currently PawPrints is being rewritten, that is what this repository is. The current site repository is here https://github.com/ritstudentgovernment/petitions. 
If you can resubmit this issue to that repository that'd be great!

**Comment by khipkin** [comment]
Huh, well that explains why this repo is so empty! 😝 Thanks.
