### ISSUE TITLE
Link metadata not petition dependent

### ISSUE THREAD

**Issue by devinmatte** [ritstudentgovernment/PawPrints-Archive#73]
Sharing links to pawprint petitions is how most of them gain traction. In order for links to get a decent amount of clickthrough they often require useful metadata to get people to click them. Currently if you post a link to a Pawprints petition, you get the main index metadata and not metadata relating to the petition itself.
![link unfurling](https://user-images.githubusercontent.com/9310513/43161529-5a2abdde-8f56-11e8-89ae-4e95b804dc69.png)

Show a snip-it of the description, title, and maybe even signature count when unfurling links instead of the base information.

**Comment by zujko** [comment]
This is being addressed in the [PAW-9](https://github.com/ritstudentgovernment/PawPrints/tree/PAW-9) branch.

Thanks for opening an issue!

**Comment by devinmatte** [comment]
Was this change ever merged into production? I'm still seeing the issue
