### ISSUE TITLE
Style and js directly embedded

### ISSUE THREAD

**Issue by devinmatte** [ritstudentgovernment/PawPrints-Archive#74]
So partially a question, and partially a comment:
Why are styles for each template embedded directly instead of importing an external stylesheet that can be cached by the browser? This going the same for javascript.

Example:
- https://github.com/ritstudentgovernment/PawPrints/blob/master/petitions/templates/index.html#L17

Cached styles and js can save a lot of load time on pages, as well as reduced data usage which matters on metered connections (mobile data).

Is there a reason why this is done this way, or was it just simply an oversight during development?

**Comment by zujko** [comment]
This was just an oversight during development. We have plans in our backlog to address this.

Thanks for opening an issue!
